services:
  - type: web
    name: laravel-app
    runtime: php
    buildCommand: "composer install && npm install && npm run build"
    startCommand: "php -S 0.0.0.0:8000 -t public"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:GENERATE_UNA_LLAVE_CON_php artisan key:generate --show
      - key: DB_CONNECTION
        value: sqlite
